databases:
  - name: CareClan-db
    plan: free
    databaseName: CareClan_production

services:
  - type: web
    name: CareClan-web
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: CareClan-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
