databases:
  - name: careclan
    plan: free
    databaseName: careclan
    user: careclan

services:
  - type: web
    name: careclan
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: careclan
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false